### ISSUE TITLE
Highlighting with PrismJS does not work in Firefox.

### ISSUE THREAD

**Issue by matcha1024** [schnerring/hugo-theme-gruvbox#35] opened 2022-11-29 13:28 UTC
Title.
The same was true on a freshly installed Firefox.
The PrismJS demo works well.
Is this a bug in Prismjs?

**Comment by schnerring** [comment] 2022-11-29 13:34
Have you tweaked your FF at all? I have the same issue with my FF, but I tweaked it using [Arkenfox user.js](https://github.com/arkenfox).

However, when I create a new FF profile, it works:

![image](https://user-images.githubusercontent.com/3743342/204542180-1d9338ed-2a2e-4687-a2ea-1a625a0cfd9c.png)

Re-installing FF doesn't purge profile data by default. Please try running `firefox -p` and creating a new profile:

![image](https://user-images.githubusercontent.com/3743342/204542038-7e4a8952-ed92-47a1-a533-6b2a7fb41b8f.png)

Then test with the new blank profile and report back.

**Comment by schnerring** [comment] 2022-11-29 13:56
Does safe-mode enable something like `privacy.resistFingerprinting` in `about:config`? If I enable that setting in my blank profile, code highlighting for the theme breaks, but the prism.js demos still work fine.

I suspect that one of the Prism plugins probably breaks when running FF in safe-mode. Maybe try disabling some of the plugins `config/_default/config.toml`:

```toml
[params.prism]
    languages = [
      # ...
    ]

    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]
```

**Comment by hyperreal64** [comment] 2022-12-16 22:13
It works when I have uBlock Origin and PrivacyBadger disabled.

**Comment by hyperreal64** [comment] 2022-12-18 01:46
If I go to the settings for uBlock Origin and PrivacyBadger and disable prefetching, the syntax highlighting works.

**Comment by mikefarmer01** [comment] 2022-12-30 10:07
Seems like the issue is related to third-party software.
Can we close it?

**Closed** 2022-12-31 13:22 UTC
