### ISSUE TITLE
Quickstart throws an error

### ISSUE THREAD

**Issue by frehburg** [schnerring/hugo-theme-gruvbox#33] opened 2022-08-18 13:55 UTC
When i follow the quickstart instructions and run hugo server i get this error message:

WARN 2022/08/18 21:53:25 Module "github.com/schnerring/hugo-theme-gruvbox" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Start building sites …
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
ERROR 2022/08/18 21:53:31 render of "home" failed: "C:\Hugo\test\layouts\index.html:5:5": execute of template failed: template: index.html:5:5: executing "main" at <partial "post-list.html" $paginator>: error calling partial: "C:\Hugo\test\layouts\partials\post-list.html:3:7": execute of template failed: template: partials/post-list.html:3:7: executing "partials/post-list.html" at <partial "post-header.html" (dict "page" . "pageIndex" $pageIndex)>: error calling partial: "C:\Hugo\test\layouts\partials\post-header.html:40:9": execute of template failed: template: partials/post-header.html:40:9: executing "partials/post-header.html" at <partial "image.html" (dict "src" .page.Params.cover.src "alt" .page.Params.cover.alt "caption" .page.Params.cover.caption "page" .page "lazy" $lazy)>: error calling partial: "C:\Hugo\test\layouts\partials\image.html:55:28": execute of template failed: template: partials/image.html:55:28: executing "partials/image.html" at <$image.Resize>: error calling Resize: image "C:\\Hugo\\test\\content\\blog\\image-optimization\\alexandre-van-thuan-mr9FouttLGY-unsplash.jpg": this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
ERROR 2022/08/18 21:53:31 render of "section" failed: "C:\Hugo\test\layouts\_default\list.html:2:5": execute of template failed: template: _default/list.html:2:5: executing "main" at <partial "post-list.html" .Paginator>: error calling partial: "C:\Hugo\test\layouts\partials\post-list.html:3:7": execute of template failed: template: partials/post-list.html:3:7: executing "partials/post-list.html" at <partial "post-header.html" (dict "page" . "pageIndex" $pageIndex)>: error calling partial: "C:\Hugo\test\layouts\partials\post-header.html:40:9": execute of template failed: template: partials/post-header.html:40:9: executing "partials/post-header.html" at <partial "image.html" (dict "src" .page.Params.cover.src "alt" .page.Params.cover.alt "caption" .page.Params.cover.caption "page" .page "lazy" $lazy)>: error calling partial: "C:\Hugo\test\layouts\partials\image.html:55:28": execute of template failed: template: partials/image.html:55:28: executing "partials/image.html" at <$image.Resize>: error calling Resize: image "C:\\Hugo\\test\\content\\blog\\image-optimization\\alexandre-van-thuan-mr9FouttLGY-unsplash.jpg": this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Error: Error building site: failed to render pages: render of "page" failed: "C:\Hugo\test\layouts\_default\single.html:3:7": execute of template failed: template: _default/single.html:3:7: executing "main" at <partial "post-header.html" (dict "page" . "pageIndex" 0)>: error calling partial: "C:\Hugo\test\layouts\partials\post-header.html:40:9": execute of template failed: template: partials/post-header.html:40:9: executing "partials/post-header.html" at <partial "image.html" (dict "src" .page.Params.cover.src "alt" .page.Params.cover.alt "caption" .page.Params.cover.caption "page" .page "lazy" $lazy)>: error calling partial: "C:\Hugo\test\layouts\partials\image.html:55:28": execute of template failed: template: partials/image.html:55:28: executing "partials/image.html" at <$image.Resize>: error calling Resize: image "C:\\Hugo\\test\\content\\blog\\image-optimization\\alexandre-van-thuan-mr9FouttLGY-unsplash.jpg": this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Built in 6226 ms

I installed hugo just 2 days ago, so i don't know what the problem would be there

my  hugo version:
hugo version

hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

**Comment by schnerring** [comment] 2022-08-18 22:43
Duplicate of #32

**Closed by schnerring** 2022-08-18 22:43 UTC
